### ISSUE TITLE
Cant upload apk to app center

### ISSUE THREAD

**Issue by irfanfadhilahkp** [wzieba/AppCenter-Github-Action#56] opened 2023-07-27 08:27 UTC
two day ago I have successful upload apk to appcenter, but now when upload to app center doesn't work send error like this.
`Error: Command distribute release --token *** --app ***/*** --group QA --file app/build/outputs/bundle/developmentDebug/*.apk --release-notes [APK-Development] *message_commit* --silent --debug is invalid`
<img width="1023" alt="image" src="https://github.com/wzieba/AppCenter-Github-Action/assets/129042690/e9922164-6213-4584-b9f6-79cb9b4f02a2">
<img width="1023" alt="image" src="https://github.com/wzieba/AppCenter-Github-Action/assets/129042690/4faeac56-d453-4fbe-aedb-335eda540aa4">

**Comment by wzieba** [comment] 2023-07-27 08:28
Duplicate of #54

**Closed as completed by wzieba** 2023-07-27 08:28 UTC
